### ISSUE TITLE
Fix mangled CSS for google map controls

### ISSUE THREAD

**Issue by poteto** [poteto/ember-getting-started#13]
It's a known bug. To fix:

``` scss
.googleMap > img {
  max-width: none;
}
```
